# Generated by Django 3.2.3 on 2022-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='order_status',
            field=models.CharField(choices=[('packed', 'Packed'), ('shipped', 'Shipped'), ('ordered', 'Ordered'), ('delivered', 'Delivered'), ('cancled', 'Cancled')], default='ordered', max_length=20),
        ),
    ]
