# Generated by Django 3.2.3 on 2022-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('cancled', 'Cancled'), ('shipped', 'Shipped'), ('packed', 'Packed')], default='ordered', max_length=20),
        ),
    ]
