# Generated by Django 3.2.3 on 2022-02-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='foodido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartmodel'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('packed', 'Packed'), ('cancled', 'Cancled')], default='ordered', max_length=20),
        ),
    ]
