# Generated by Django 3.2.3 on 2022-02-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220226_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='foodido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodmodel'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('cancled', 'Cancled'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='ordered', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='userido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cartmodel'),
        ),
    ]
