# Generated by Django 3.2.3 on 2022-02-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220226_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='foodid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('packed', 'Packed'), ('cancled', 'Cancled')], default='ordered', max_length=20),
        ),
    ]
