# Generated by Django 3.2.3 on 2022-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220226_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='amount',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('cancled', 'Cancled'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('ordered', 'Ordered')], default='ordered', max_length=20),
        ),
    ]
