# Generated by Django 3.2.3 on 2022-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220226_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='foodname',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('shipped', 'Shipped'), ('packed', 'Packed'), ('cancled', 'Cancled'), ('ordered', 'Ordered')], default='ordered', max_length=20),
        ),
    ]
