# Generated by Django 3.2.3 on 2022-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220226_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='addressline1',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='customermodel',
            old_name='pincode',
            new_name='stream',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='state',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('cancled', 'Cancled'), ('shipped', 'Shipped'), ('packed', 'Packed'), ('delivered', 'Delivered'), ('ordered', 'Ordered')], default='ordered', max_length=20),
        ),
    ]
