# Generated by Django 3.2.3 on 2022-03-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220301_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='stream',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('ordered', 'Ordered'), ('cancled', 'Cancled'), ('delivered', 'Delivered'), ('packed', 'Packed')], default='ordered', max_length=20),
        ),
    ]
