# Generated by Django 3.2.3 on 2022-03-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220301_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('cancled', 'Cancled'), ('shipped', 'Shipped'), ('packed', 'Packed'), ('ordered', 'Ordered')], default='ordered', max_length=20),
        ),
    ]
