# Generated by Django 3.2.3 on 2022-03-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220301_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('packed', 'Packed'), ('ordered', 'Ordered'), ('shipped', 'Shipped'), ('cancled', 'Cancled'), ('delivered', 'Delivered')], default='ordered', max_length=20),
        ),
    ]
