# Generated by Django 3.2.3 on 2022-03-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='semester',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('packed', 'Packed'), ('ordered', 'Ordered'), ('delivered', 'Delivered'), ('cancled', 'Cancled'), ('shipped', 'Shipped')], default='ordered', max_length=20),
        ),
    ]
